[app]
data_dir = "data"
max_recs = 2000
date_fmt = "%Y-%m-%d %H:%M:%S"
leetcode_graphql_url = "https://leetcode.com/graphql"
n_api_retries = 3

[parsing]
min_base_offer = 2
max_base_offer = 120
min_total_offer = 3
max_total_offer = 200

[llms]
ollama_model = "llama3:8b-instruct-q6_K"
openrouter_model = "meta-llama/llama-3-8b-instruct:free"
openrouter_url = "https://openrouter.ai/api/v1/chat/completions"
openrouter_req_per_min = 20
